---
apiVersion: v1
kind: Service
metadata:
  name: parity-processbot
  namespace: {{ .Values.app.KUBE_NAMESPACE }}
  labels:
    app: parity-processbot
spec:
  ports:
    - name: backend
      port: {{ .Values.app.WEBHOOK_PORT }}
  selector:
    app: parity-processbot
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: parity-processbot
  namespace: {{ .Values.app.KUBE_NAMESPACE }}
  labels:
    app: parity-processbot
spec:
  selector:
    matchLabels:
      app: parity-processbot
  serviceName: parity-processbot
  updateStrategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: parity-processbot
    spec:
      volumes:
      - name: processbot-key-volume
        secret:
          secretName: processbot-key
          defaultMode: 256
      - name: storage
        persistentVolumeClaim:
          claimName: processbot-pv-claim
      containers:
      - name: parity-processbot
        imagePullPolicy: Always
        image: paritytech/processbot:{{ .Values.app.DOCKER_TAG }}
        volumeMounts:
        - name: processbot-key-volume
          mountPath: "/etc/processbot-key"
          readOnly: true
        - name: storage
          mountPath: {{ .Values.config.storagePath }}
        ports:
        - name: backend
          containerPort: {{ .Values.app.WEBHOOK_PORT }}
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.app.WEBHOOK_PORT }}
          initialDelaySeconds: 15
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.app.WEBHOOK_PORT }}
          initialDelaySeconds: 15
          periodSeconds: 5
        env:
            - name: RUST_BACKTRACE
              value: full
            - name: RUST_LOG
              value: debug
            - name: GITLAB_URL
              value: {{ .Values.app.GITLAB_URL }}
            - name: GITLAB_ACCESS_TOKEN
              value: {{ .Values.app.GITLAB_ACCESS_TOKEN }}
            - name: INSTALLATION_LOGIN
              value: {{ .Values.app.INSTALLATION_LOGIN }}
            - name: PRIVATE_KEY_PATH
              value: "/etc/processbot-key/PROCESSBOT_KEY"
            - name: WEBHOOK_PORT
              value: {{ quote .Values.app.WEBHOOK_PORT }}
            - name: START_FROM_CWD
              value: {{ quote .Values.app.START_FROM_CWD }}
            - name: GITHUB_APP_ID
              value: {{ quote .Values.app.GITHUB_APP_ID }}
            - name: DB_PATH
              value: {{ .Values.config.storagePath }}/db
            - name: REPOSITORIES_PATH
              value: {{ .Values.config.storagePath }}/repositories
            - name: WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: WEBHOOK_SECRET

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: processbot-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
