---
# Ingress for the webhook
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: processbot-ingress
  namespace: {{ .Values.app.KUBE_NAMESPACE }}
  labels:
    app: parity-processbot
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  rules:
  - host: {{ .Values.ingress.domain }}
    http:
      paths:
      - backend:
          service:
            name: parity-processbot
            port:
              number: {{ .Values.app.WEBHOOK_PORT }}
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - {{ .Values.ingress.domain }}
    secretName: {{ .Values.ingress.domain }}
