pub mod auto_merge;
pub mod bamboo;
pub mod bots;
pub mod config;
pub mod constants;
//pub mod db;
pub mod duration_ticks;
pub mod error;
pub mod github;
pub mod github_bot;
pub mod http;
//pub mod issue_assignment;
//pub mod issue_missing;
//pub mod issue_project;
//pub mod local_state;
pub mod matrix;
pub mod matrix_bot;
pub mod process;
//pub mod review;
//pub mod status;
pub mod webhook;

pub type Result<T> = std::result::Result<T, error::Error>;
